# “YieldExceptionYield” (Решение)

## Ответ

```
Foo
1
```

## Ссылки

* [Eric Lippert: Iterator Blocks, Part Five: Push vs Pull](http://blogs.msdn.com/b/ericlippert/archive/2009/07/23/iterator-blocks-part-five-push-vs-pull.aspx)
* [Dan Crevier: Yield and usings - your Dispose may not be called!](http://blogs.msdn.com/b/dancre/archive/2008/03/14/yield-and-usings-your-dispose-may-not-be-called.aspx)
* [StackOverflow: yield return with try catch, how can i solve it](http://stackoverflow.com/questions/5067188/yield-return-with-try-catch-how-can-i-solve-it)
* [StackOverflow: Yield return from a try/catch block](http://stackoverflow.com/questions/7245150/yield-return-from-a-try-catch-block)
* [StackOverflow: Finally block may not be called when enumerating over yielding method](http://stackoverflow.com/questions/19930294/finally-block-may-not-be-called-when-enumerating-over-yielding-method)
* [StackOverflow: Yield return from a try/catch block](http://stackoverflow.com/questions/7245150/yield-return-from-a-try-catch-block)

[Задача](./YieldExceptionYield-P.md)